name: Go

on:
  push:
    branches: [ main, staging ]
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/go.yml'
      - 'docs/**'
  pull_request:
    branches: [ main, staging ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Compress output
      run:  tar -zcvf me.tar.gz ./output
        
    # extract branch name
    - name: Extract branch name
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    # extract branch name on pull request
    - name: Print branch name
      if: github.event_name == 'pull_request'
      run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
      
    - name: version
      run: echo "::set-output name=version::$(./me --version)"
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    # Create release from tag
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          me.tar.gz
